### ISSUE TITLE
Using `alwayssendto` can mess up privacy group ID calculation

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/orion#350]
Orion has the alwayssendto config option to specify a list of public keys that should always be included in the "to" field of a Send request.

When using private transactions, Orion uses the from and to fields in the SendRequest to calculate the privacy group ID.

The problem here is that Orion will evaluate the alwayssendto property BEFORE calculating the private group ID. It will end up using the public keys specified in the alwayssendto property as part of the privacy group ID calculation.

In this scenario, if in a network there are Orion nodes with different alwayssendto config values, they'll never have a consistent privacy group ID.

Also, if at any point in time the user changes the value of alwayssendto property, all private group IDs previously calculated won't be the same (assuming the same input to and from fields on the SendRequest).

Probability: Occasional 
Severity: Critical

From @rojotek on the original JI: 
> I think we should either exclude the always send to from the privacy group calculation, or maybe just remove the feature.

**Comment by MadelineMurray** [comment]
Look at excluding from the privacy group calculation. Will do this until the effort is big.

**Comment by MadelineMurray** [comment]
Steps to reproduce (legacy/EEA privacy): 
1. Set `alwayssendto` and send transaction to another Orion node 
2. Change `alwayssendto` to another value and send a transaction to the same recipients as in 1.
3. See if they have the different privacy group IDs

**Comment by pinges** [comment]
I've checked the code and did an experiment with three nodes, A, B, and C. First A had an alwayssendto to C. A then sent a legacy transaction to itself, creating the legacy privacy group containing only itself. priv_findPrivacyGroup finds this privacy group with the privacyGroupId "MC4aHjApHsGb0j5glU2iAj5KcR5LId52S0BU9mtdeuY=".
Deleting the database and restarting the three nodes, but this time with A having an alwayssendto to B results in the same privacyGroupId.
This issue can be closed.

**Comment by MadelineMurray** [comment]
Confirmed this is no longer occurring by sending a `privateFor` transaction with and without `alwayssendto` defined.
