### ISSUE TITLE
Enabling TLS for client connection throws exception

### ISSUE THREAD

**Issue by magooster** [PegaSysEng/orion#358]
Hi according to the docs when starting up orion with clientconnectiontls strict, the server certificate and corresponding key should be generated if missing however the following exception is thrown 

io.vertx.core.VertxException: io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: /var/orion/client-connection-tls-server-key.pem

Looking at Orion.java seems certificate and key only generated when tls is set to strict for the Orion to Orion endpoint (external)

Orion version 1.5.0

**Comment by usmansaleem** [comment]
Fixed as part of #377. No documentation change required.
