### ISSUE TITLE
clientconnectiontlsserverchain setting not applied

### ISSUE THREAD

**Issue by magooster** [PegaSysEng/orion#359]
The clientconnectiontlsserverchain setting is not applied when creating the client httpserver

In Orion.java in package net.consensys.orion.cmd

`if ("strict".equals(config.clientConnectionTls())) {
        final Path tlsServerCert = workDir.resolve(config.clientConnectionTlsServerCert());
        final Path tlsServerKey = workDir.resolve(config.clientConnectionTlsServerKey());
        final PemKeyCertOptions pemKeyCertOptions = new PemKeyCertOptions().setKeyPath(tlsServerKey.toString()).setCertPath(tlsServerCert.toString());
        clientOptions.setSsl(true);
        clientOptions.setClientAuth(ClientAuth.REQUIRED);
        clientOptions.setPemKeyCertOptions(pemKeyCertOptions);

         Typo here -> options.setPemTrustOptions(createPemTrustOptions(config.clientConnectionTlsServerChain()));

        createTrustOptions(
            config.clientConnectionTlsServerTrust().toLowerCase(),
            config.clientConnectionTlsKnownClients()).ifPresent(clientOptions::setTrustOptions);
      }`

highlighted line should be

clientOptions.setPemTrustOptions(createPemTrustOptions(config.clientConnectionTlsServerChain()));

**Comment by MadelineMurray** [comment]
Thanks for taking the time to raised - fixed in #360
